### PR TITLE
Fix Galley WeakHashMap ReentrantLock maps

### PR DESCRIPTION
**Pull request by ruhan1**

### CODE REVIEW

**Comment by ruhan1** [comment]
retest this please

**Comment by ruhan1** [comment]
CI failed. It seems Galley pr build does not pick up the latest Weft snapshot (https://github.com/Commonjava/weft/pull/17). @bxf12315 can you help look at it?

**Comment by ruhan1** [comment]
retest this please

**Comment by jdcasey** [comment]
retest this please

**Comment by ruhan1** [comment]
retest this please

**Comment by ruhan1** [comment]
retest this please

**Comment by ruhan1** [comment]
retest this please

**Pull request merged**
