### PR TITLE
Update weft to 1.10 and set some load parameters

### PR DESCRIPTION
**Pull request by ligangty**

### CODE REVIEW

**Comment by ruhan1** [comment]
retest this please

**Comment by ruhan1** [comment]
This is weird. I saw https://repo1.maven.org/maven2/org/commonjava/cdi/util/weft/1.10/ is ready. but the build cannot find it.

**Comment by ligangty** [comment]
retest this please.

**Comment by ligangty** [comment]
There is new weft version so will update to new version in other pr.

**Pull request closed without merging**
