### PR TITLE
FIX: perfect some tiny tweak for NOS-544

### PR DESCRIPTION
**Pull request by yma88**

### CODE REVIEW

**Comment by jdcasey** [comment]
Looks like there's some deadlock biting us here. I think it could be in partyline, but not sure.

**Comment by jdcasey** [comment]
retest this please

**Comment by yma88** [comment]
Hi, @jdcasey 
I mvn build in local successfully and check the output log and no dead lock found, could you point it out? or I could change the code accordingly.
While, I re build again, the mvn build process sometime would be blocked by Running org.commonjava.maven.galley.cache.infinispan.FastLocalCacheProviderConcurrentTest, very occasionally, I'm not sure if it's the issue you said.

**Comment by jdcasey** [comment]
@yma88 I think the problem is the deadlock that @ligangty has been wrestling with.

**Comment by jdcasey** [comment]
retest this please

**Comment by jdcasey** [comment]
@yma88 I just merged a new PR for partyline which I'm hoping will help with this build.

**Pull request merged**
